<script type="text/javascript">
    var latkeConfig = {
      "staticServePath": "",
      "servePath": ""
    };
    
    var qiniu = {
        "qiniuUploadToken": "",
        "qiniuDomain": ""
    };
    
    var Label = {
        "skinDirName": "9IPHP",
        "editorType": "CodeMirror-Markdown",
        "userRole": "adminRole",
        "PAGE_SIZE": "20",
        "WINDOW_SIZE": "15",
        "localeString": "zh_CN",
        "version": "2.0.0",
        "miniPostfix": "",
        "reportIssueLabel": "please report this issue on https://github.com/b3log/solo/issues/new",
        "noDataLabel": "该列表很懒，什么都没有留下。。。",
        "linkDescriptionLabel": "链接描述",
        "addressInvalidLabel": "请以协议开头，如: http://",
        "selectLabel": "选择",
        "outOfDateLabel":　"您的 Solo 过时了 ;-(，请下载最新版本：",
        "upToDateLabel": "您正在使用最新的 Solo ;-)",
        "commentContentLabel": "评论内容",
        "loadingLabel": "载入中....",
        "noCommentLabel": "暂无评论",
        "confirmRemoveLabel": "是否删除",
        "removeLabel": "删除",
        "cancelPutTopLabel": "取消置顶",
        "putTopLabel": "置顶",
        "viewLabel": "浏览",
        "updateLabel": "更新",
        "commentLabel": "评论",
        "titleLabel": "标题",
        "tagsLabel": "标签",
        "authorLabel": "作者",
        "createDateLabel": "创建日期",
        "previousPageLabel": "上一页",
        "pageLabel": "页面",
        "nextPagePabel": "下一页",
        "gotoLabel": "跳转",
        "fileNameLabel": "文件名",
        "uploadDateLabel": "上传日期",
        "sizeLabel": "大小",
        "downloadCountLabel": "下载次数",
        "downloadLabel": "下载",
        "permalinkLabel": "链接",
        "titleEmptyLabel": "标题不能为空！",
        "contentEmptyLabel": "内容不能为空！",
        "linkTitleLabel": "链接标题",
        "urlLabel": "URL",
        "addressEmptyLabel": "地址不能为空！",
        "pluginNameLabel": "插件名",
        "statusLabel": "状态",
        "versionLabel": "版本",
        "commentNameLabel": "姓名",
        "commentEmailLabel": "邮箱",
        "roleLabel": "角色",
        "administratorLabel": "管理员",
        "duplicatedEmailLabel": "邮件地址重复！",
        "mailInvalidLabel": "邮箱格式不正确！",
        "mailCannotEmptyLabel": "邮箱不能为空！",
        "noSettingLabel": "该博客无账号，请添加",
        "blogEmptyLabel": "请选择博客服务！",
        "sumLabel": "共",
        "countLabel": "篇",
        "blogArticleEmptyLabel": "请选择需要导入的文章",
        "importSuccLabel": "导入成功 :-)",
        "categoryLabel": "分类",
        "importedLabel": "已导入",
        "passwordEmptyLabel": "密码不能为空！",
        "tagsEmptyLabel": "标签不能为空！",
        "abstractEmptyLabel": "摘要不能为空！",
        "commonUserLabel": "一般用户",
        "articleLabel": "文章",
        "enabledLabel": "已启用",
        "disabledLabel": "已禁用",
        "signIsNullLabel": "该签名档为空",
        "editorLeaveLabel": "编辑器中还有内容，是否离开？",
        "editorPostLabel": "编辑器中还有内容，是否清空？",
        "enableLabel": "启用",
        "disableLabel": "禁用",
        "settingLabel": "设置",
        "linkEmptyLabel": "链接不能为空",
        "openMethodLabel": "页面打开方式",
        "typeLabel": "类型",
        "markdownHelpLabel": "<dl><dt>标题</dt><dd> # 一级标题</dd><dd> #### 四级标题</dd></dl><dl><dt>链接</dt><dd>[链接文字](链接地址)</dd></dl><dl><dt>强调</dt><dd>*斜体* 或者 _斜体_</dd><dd>**粗体** 或者 __粗体__</dd><dd>***粗体+斜体*** 或者 ___粗体+斜体___</dd></dl><dl><dt>列表</dt><dt></dt><dd>* 无序</dd><dd>1. 有序</dd></dl><dl><dt>代码</dt><dd>`var markDown = undefined`</dd></dl><dl><dt>图片</dt><dd>![alt text](/path/to/img.jpg 'Title')</dd></dl><dl><dt><a href='http://daringfireball.net/projects/markdown/syntax' target='_blank'>完整语法</a></dt></dl>",
        "notFoundLabel": "找不到！",
        "em00Label": "微笑",
        "em01Label": "大笑",
        "em02Label": "高兴",
        "em03Label": "悲伤",
        "em04Label": "哭泣",
        "em05Label": "无语",
        "em06Label": "烦躁",
        "em07Label": "生气",
        "em08Label": "我瞅",
        "em09Label": "惊讶",
        "em10Label": "酷",
        "em11Label": "顽皮",
        "em12Label": "爱心",
        "em13Label": "心碎",
        "em14Label": "魔鬼",
        "paramSettingsLabel": "参数设置",
        "nonNegativeIntegerOnlyLabel": "只能为非负整数！",
        "indexTagDisplayCntLabel": "首页标签显示数",
        "indexRecentCommentDisplayCntLabel": "最新评论显示数目",
        "indexMostCommentArticleDisplayCntLabel": "评论最多文章显示数目",
        "indexMostViewArticleDisplayCntLabel": "访问最多文章显示数目",
        "pageSizeLabel": "分页每页显示文章数",
        "windowSizeLabel": "分页页码最大宽度",
        "randomArticlesDisplayCntLabel": "随机阅读显示数目",
        "relevantArticlesDisplayCntLabel": "相关阅读显示数目",
        "externalRelevantArticlesDisplayCntLabel": "站外相关阅读显示数目",
        "nameTooLongLabel": "姓名只能为 2 到 20 个字符！",
        "navLabel": "导航",
        "userLabel": "用户",
        "changeRoleLabel": "改变角色",
        "visitorUserLabel": "访客用户",
        "categoryTooLongLabel": "分类名称只能为 2 到 32 个字符！",
        "descriptionLabel": "描述",
        "autoSaveLabel": "自动保存",
        "addBoldLabel": '添加粗体',
        "addItalicLabel": '添加斜体',
        "insertQuoteLabel": '插入引用',
        "addBulletedLabel": '添加无序列表',
        "addNumberedListLabel": '添加有序列表',
        "addLinkLabel": '添加链接',
        "undoLabel": '撤销',
        "redoLabel": '恢复',
        "previewLabel": '预览',
        "helpLabel": '帮助',
        "fullscreenLabel": '全屏',
        "uploadFilesLabel": '上传文件'

    };    
    
    admin.init();
</script>